### ISSUE TITLE
Add jQuery + jQuery UI

### ISSUE THREAD

**Issue by sprynm** [EngageSoftware/DNN-JavaScript-Libraries#31]
First, thanks for all your work on this repo Brian.

Are you interested in adding libraries typically handled by DNN Corp? Evoq 9 still uses jQ 1.9.1 which has a number of deficiencies.

**Comment by bdukes** [comment]
Historically I've avoided those libraries, but we've occasionally had need for them, too, so I'm okay with allowing them now.  Do you have specific versions of jQuery and UI, or just latest?

**Comment by bdukes** [comment]
@sprynm I've added https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery_1.12.4, https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery_2.2.4, and https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery_3.2.1, does that meet what you're looking for?

**Comment by bdukes** [comment]
I've also added https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery-UI_1.12.1, and I'm going to republish those jQuery packages b/c they are setup to load at the bottom of the `</body>` instead of in the `<head>`

**Comment by bdukes** [comment]
- https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery_1.12.4_fix
- https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery_2.2.4_fix
- https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery_3.2.1_fix

**Comment by sprynm** [comment]
Brian, really sorry to miss your posts.  Thank you!
