### ISSUE TITLE
Resources.zip specified in manifest but not created

### ISSUE THREAD

**Issue by can-anierzad** [EngageSoftware/DNN-JavaScript-Libraries#44]
When creating a new library that doesn't require any resources to be specified in `dnn-library.json` the `resources` array is present but empty. The generated manifest still has a node for `Resources.zip` which is never created. Results in install failure as DNN can't find `Resources.zip`.

Am I using this wrong? Should there always be something specified in the `resources` array inside `dnn-library.json`?

**Comment by bdukes** [comment]
Sorry, that's an undocumented manual step.  If you don't have any resources, you need to remove the `Resources` component from the `dnn` file.
