### ISSUE TITLE
Error running `yarn run new`

### ISSUE THREAD

**Issue by seek78** [EngageSoftware/DNN-JavaScript-Libraries#698]
Hi,
trying to run the generator for Bootstrap, I'm facing with: 

`Cannot find package 'yeoman-generator' imported from C:\GitHub\DNN-JavaScript-Libraries\_new\index.mjs`

I'm quite sure to have installed all NPM's required packages.

Thanks,
S.

**Comment by bdukes** [comment]
Did `yarn install` complete successfully?

There's already a bootstrap package, so you don't need to run the generator to create it.

**Comment by bdukes** [comment]
I've created [a release for Bootstrap 5.3.1](https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/bootstrap_5.3.1). This has the package from the artifacts of [the GitHub Actions run](https://github.com/EngageSoftware/DNN-JavaScript-Libraries/actions/runs/5668109307) for [the PR to bump the Bootstrap version](https://github.com/EngageSoftware/DNN-JavaScript-Libraries/pull/680).

Hope it helps!

**Comment by seek78** [comment]
> Did `yarn install` complete successfully?
> 
> There's already a bootstrap package, so you don't need to run the generator to create it.

Yes, for sure.



> I've created [a release for Bootstrap 5.3.1](https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/bootstrap_5.3.1). This has the package from the artifacts of [the GitHub Actions run](https://github.com/EngageSoftware/DNN-JavaScript-Libraries/actions/runs/5668109307) for [the PR to bump the Bootstrap version](https://github.com/EngageSoftware/DNN-JavaScript-Libraries/pull/680).
> 
> Hope it helps!

Now I understand!
I tried clicking on the releases link [here](https://github.com/EngageSoftware/DNN-JavaScript-Libraries#packages), but being wrong I tried to generate a new package!

Thanks!
S.
